import 'dart:async';
import 'package:floor/floor.dart';
import 'Flights.dart';
import 'FlightDAO.dart';
import 'package:sqflite/sqflite.dart' as sqflite;

///This is partial class.
///The rest code of Database will be generated by tools in this part.
part 'FlightsDatabase.g.dart';

///FlightsDatabase defines the Floor database for managing Flights.
@Database(version: 2, entities: [Flights])
abstract class FlightsDatabase extends FloorDatabase{

  ///creates a function returning a DAO object.
  ///"get" generates this function as a getter to access to the FlightDAO.
  FlightDAO get getDao;

}

